# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Authentication-Store-RDBO
version:      0.001
version_from: lib/Catalyst/Plugin/Authentication/Store/RDBO.pm
installdirs:  site
requires:
    Catalyst::Plugin::Authentication: 0
    Rose::DB::Object:              0
    Set::Object:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
